server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: poopberry
          uri: http://localhost:8081
          predicates:
            - Path=/customers/**

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: api-gateway
    description: Spring Cloud Gateway Application
    version: 1.0.0